### ISSUE TITLE
Monoid Css

### ISSUE THREAD

**Issue by ocharles** [sebastiaanvisser/clay#101]
There's a clear `Monoid` instance for `Css` - could we have it added?

```haskell
instance Monoid Css where
  mempty = pure ()
  mappend = liftA2 mappend
```

**Comment by tonyday567** [comment]
I had:

    instance Monoid Css where
        mempty = return ()
        mappend a b = a >> b

I suppose applicatival trumps monadal these days.

**Comment by ibotty** [comment]
Just noticed, that that issue can be closed, right?

**Comment by tonyday567** [comment]
Sure can!
