### ISSUE TITLE
Any way to add !important?

### ISSUE THREAD

**Issue by andrewthad** [sebastiaanvisser/clay#107]
Is there a way to add the `!important` suffix in Clay? I don't see anything in the docs, but it seems unlikely that this would be missing. To clarify, I'm trying to do something like this:

```
p {
  color: red !important;
}
```

**Comment by i-breaker** [comment]
("display" -: "none !important")

**Comment by dbaynard** [comment]
@andrewthad From 0.12.3

```haskell
p ? do
  important $ color red
```

**Comment by andrewthad** [comment]
thanks!
