### ISSUE TITLE
Publish new clay version

### ISSUE THREAD

**Issue by marcelbuesing** [sebastiaanvisser/clay#110]
Could you please publish a new version of clay, including the latest commits ? That would be great.

**Comment by BartAdv** [comment]
Yeah, I needed to do some flexbox stuff and to my surprise none of it was in the published version. Fortunately one can still use escape hatches (or point to certain revision if using stack for example), but still, seems like it's been quite a time since those things were merged.

**Comment by 3noch** [comment]
:+1:

**Comment by int-index** [comment]
+1 Flexbox support.

**Comment by montagy** [comment]
where is the maintainer?

**Comment by montagy** [comment]
no maintainer?

**Comment by seanparsons** [comment]
I'm ostensibly one of the maintainers last I checked, but I've been super busy of recent.

**Comment by seanparsons** [comment]
Long overdue, but I've pushed 0.11.

**Comment by marcelbuesing** [comment]
Awesome! Thank you so much :)
