### ISSUE TITLE
Setting unitless values for lineHeight

### ISSUE THREAD

**Issue by bryangarza** [sebastiaanvisser/clay#112]
I haven't been able to do:
``` haskell
lineHeight 1
```
Because it gives:
```
    No instance for (Num (Size a0)) arising from the literal ‘1’
    The type variable ‘a0’ is ambiguous
    Note: there are several potential instances:
      instance Num (Size Rel) -- Defined in ‘Clay.Size’
      instance Num (Size Abs) -- Defined in ‘Clay.Size’
    In the first argument of ‘lineHeight’, namely ‘1’
    In a stmt of a 'do' block: lineHeight 1
    ...
Failed, modules loaded: none.
```
Making it `lineHeight (1 :: Size Rel)` or `lineHeight (1 :: Size Rem)` doesn't give the right CSS, that does `line-height : 1%` and `line-height : 1px`, respectively.

So instead I've been using `other` for all the `lineHeight` calls:
``` haskell
lineHeight (other "1")
```
Am I doing something wrong? `line-height` is one of those CSS properties where having a unitless size is the best practice.

**Comment by marcelbuesing** [comment]
How about ```lineHeight (pct 100)``` ? Not sure though if that behaves differently.

**Comment by marcelbuesing** [comment]
Ok apparently it does behave differently [stackoverflow](http://stackoverflow.com/questions/20695333/why-does-unitless-line-height-behave-differently-from-percentage-or-em-in-this-e).

**Comment by CodyReichert** [comment]
I think what you're looking for is `unitless`

https://github.com/sebastiaanvisser/clay/blob/master/src/Clay/Size.hs#L80

**Comment by bryangarza** [comment]
I know about `unitless` but

``` haskell
lineHeight (unitless 1)
```

Gives `Not in scope: 'unitless'`, even when importing `Clay.Size`

**Comment by CodyReichert** [comment]
As far as I know, `unitless` new and not on Hackage. So unless you're pulling in Clay from Github, that's correct. http://hackage.haskell.org/package/clay-0.10.1/docs/Clay-Size.html

**Comment by bryangarza** [comment]
Ah, that must be it 👍 I'll install Clay directly from Git.
