### ISSUE TITLE
px should accept Doubles, not Integers

### ISSUE THREAD

**Issue by ocharles** [sebastiaanvisser/clay#113]
It's valid to have real numbers as `px` values, not just integers.

**Comment by bobjflong** [comment]
I'm pretty sure `px` now accepts Doubles so this could be closed.

**Comment by turion** [comment]
True. See https://hackage.haskell.org/package/clay-0.13.1/docs/Clay-Size.html#v:px. `px :: Double -> Size LengthUnit`
