### ISSUE TITLE
Alpha value of Rgba and Hsla should be a Double or Float between 0 and 1

### ISSUE THREAD

**Issue by psfblair** [sebastiaanvisser/clay#114]
The source for Clay.Color has the alpha values as Integers and does some pattern matching indicating that it is conceived of as a value between 0 and 255. The w3c says that the alpha values are decimal fractions of 1. (See http://www.w3.org/wiki/CSS/Properties/color/RGBA and http://www.w3.org/wiki/CSS/Properties/color/HSLA ).

**Comment by montagy** [comment]
+1
Integer cant satisfy needs.

**Comment by seanparsons** [comment]
Done.
