### ISSUE TITLE
rendering inline styles

### ISSUE THREAD

**Issue by emmanueltouzery** [sebastiaanvisser/clay#120]
I'm using `clay` to render inline styles, in the HTML, like so:

    <div style="margin-top: 10px">

it works well, but I couldn't find a "good" api for that. `renderWith compact []` is still generating the `{}` around the style, which I have to remove with `tail . init`. Is there is a better way which I've missed? If not, it would be nice to support this use case from the library.

**Comment by phadej** [comment]
I run into this issue myself, haven't found better approach `tail .init` myself either :(

**Comment by bobjflong** [comment]
Me too, note that `{margin-top:10px}` is not valid CSS. Proposed a new `htmlInline` configuration [here](https://github.com/sebastiaanvisser/clay/pull/127).

**Comment by phadej** [comment]
This is awesome, thanks!
