### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by chrisdone** [sebastiaanvisser/clay#13]
Why is the border stuff in a different order to normal order? Instead of

```
border-left: 1px solid #aaa 
```

in Clay you instead write:

```
borderLeft solid (px 1) "#aaa"
```

For convenient partial application? It's rather jarring to have the args swapped from normal.

**Comment by adius** [comment]
Uhm, can we please fix this!?
It seems like the wrong order is only implemented due to goodwill, but it's not specified, right?

**Comment by MurakamiKennzo** [comment]
Anything else? Currently It's type also the wrong order.

**Comment by turion** [comment]
Yes, it seems like the issue was never actually fixed. Thanks for spotting. PRs welcome to fix!
