### ISSUE TITLE
"API Documentation" link on homepage is dead

### ISSUE THREAD

**Issue by anderspapitto** [sebastiaanvisser/clay#134]
when I follow the link at the bottom of http://fvisser.nl/clay/ I see

```
Not Found

There is no documentation for clay-0.12. See https://hackage.haskell.org/package/clay/docs/Clay.html for the latest version.
```

following that suggested link doesn't work either

**Comment by seanparsons** [comment]
Hmmm, sometimes those docs on Hackage lag a little, but this one should totally be up by now. Gah.

**Comment by seanparsons** [comment]
Should be sorted now, thanks for notifying us!
