### ISSUE TITLE
Auto causes an infinite loop on Clay 0.12

### ISSUE THREAD

**Issue by psosera** [sebastiaanvisser/clay#135]
The following code snippet produces an infinite loop on Clay version 0.12:

~~~ {.haskell}
module Main where

import Clay

main = putCss $ do
  body ? do
    marginLeft auto
~~~

Clay version 0.11 accepts this code and produces the expected output:

~~~
body
{
  margin-left : auto;
}


/* Generated with Clay, http://fvisser.nl/clay */
~~~

**Comment by seanparsons** [comment]
More minimal reproducing code (for my own reference mainly):

`putCss $ marginLeft auto`

**Comment by dbaynard** [comment]
Hello, would you kindly upload a new version to hackage, fixing this issue?

**Comment by seanparsons** [comment]
@dbaynard Apologies, 0.12.1 is now deployed to Hackage.
