### ISSUE TITLE
Support Paged Media

### ISSUE THREAD

**Issue by dbaynard** [sebastiaanvisser/clay#137]
Hello,

Clay is already nearly there when it comes to supporting paged media, for use with `@media print` in browsers or dedicated typesetters such as [Prince](//www.princexml.com).

Many of the changes are simply adding combinators; a suitable `Clay.Paged` module might be suitable.

One change is more substantial. `@page` queries can take nested css, like `@media` queries. For example, the following displays the line "This page is intentionally left blank" at the top of any page which has the associated pseudo-selector `blank`.

```css
@page :blank {
  @top-center { content: "This page is intentionally left blank." }
}
```

It looks like extending, replacing or complementing the `query` functions to handle more than just `media` queries would be the best way to go about implementing this. As it stands my workaround involves wrapping the `@top-center { … }` using a monster regular expression in vim.

It would be good to fully support the CSS paged media spec. How would this best be done?

---

See <https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/> for a good description of the capabilities.

**Comment by dbaynard** [comment]
Would a PR with `Clay.Paged` be an acceptable addition to the API?

How about adding the function implementing the `@page` functionality?

**Comment by seanparsons** [comment]
That sounds like a reasonable approach.

**Comment by turion** [comment]
@dbaynard do you want to create a PR?

**Comment by JonathanReeve** [comment]
Any progress on this? This would be really nice to have.

**Comment by turion** [comment]
@JonathanReeve If someone creates a PR I'll review and merge.

@dbaynard are you still interested?

**Comment by dbaynard** [comment]
Hello, please forgive my delay. I was keen in 2017; I'm now not sure I'll be using clay, in future. It looks like I should respond on #173, first; if that is a positive experience all round, I'll put together a plan, at least, for this feature.
