### ISSUE TITLE
Incorrect value for sResize and wResize?

### ISSUE THREAD

**Issue by ryantrinkle** [sebastiaanvisser/clay#138]
These don't look quite right to me: https://github.com/sebastiaanvisser/clay/blob/a887456c5e6deee59f94440d3b615754dcea67eb/src/Clay/Display.hs#L275-L276

**Comment by seanparsons** [comment]
Agreed.

**Comment by seanparsons** [comment]
Fixed in 0.12.2.

**Comment by seanparsons** [comment]
Fixed in 0.12.2.

**Comment by ryantrinkle** [comment]
Thanks!
