### ISSUE TITLE
boxShadow none

### ISSUE THREAD

**Issue by waddlaw** [sebastiaanvisser/clay#144]
My test code following:

```
{-# LANGUAGE OverloadedStrings #-}

import Clay

main :: IO ()
main =
  putCss $ do
    a # ".contact" ? do
      boxShadow (px 2) (px 2) nil "#555"
      hover & boxShadow none
```

`boxShadow none` is invalid code.
but, I want to this.

What should I do?

**Comment by 3noch** [comment]
You will likely have to make this one yourself. But it's easy. Inspecting the source led to this:

```haskell
import Clay.Stylesheet
prefixed (browsers <> "box-shadow") ("none" :: Value)
```

**Comment by waddlaw** [comment]
@3noch thanks a lot!

`Clay` doesn't export `prefixed`...
`Clay.Stylesheet` very useful for me.
I didn't know that at all!

thanks.

**Comment by 3noch** [comment]
@waddlaw Glad to help. I still think it'd be much better if there were a nice API for this.
