### ISSUE TITLE
Support box-shadow with none, initial, and inherit

### ISSUE THREAD

**Issue by 3noch** [sebastiaanvisser/clay#146]
As evidenced by #144, it's not easy to use `none`, `initial`, and `inherit` with `box-shadow`. Can we add an API for these? Even if it just accepted an arbitrary string argument, it would be better than having to reconstruct the logic by reading the source.

**Comment by dbaynard** [comment]
@3noch In 0.12.3

```haskell
boxShadow none
boxShadow initial
boxShadow inherit
```

**Comment by 3noch** [comment]
@dbaynard Thank you!
