### ISSUE TITLE
Render css comments (enhancement)

### ISSUE THREAD

**Issue by dbaynard** [sebastiaanvisser/clay#149]
Sometimes it is useful for output css to have comments. Also is is occasionally useful to have commented out css.

---

It would be good to have one function that adds a comment.
```haskell
comment :: Text -> Css
```
It may be useful to specify during pretty-printing how this comment should be appended to the previous element (same line, end of line).

It would also be helpful to have a function which comments out code, as (for example) this then becomes visible (with strikeout) in chrome developer tools.
```haskell
commented :: Css -> Css
```

Names to be bikeshedded.

I can implement if it would be valuable (just not for another few weeks).

**Comment by seanparsons** [comment]
@dbaynard I'm entirely happy to entertain a PR for this, I can imagine how it would be useful.

**Comment by dbaynard** [comment]
I've done the relatively straightforward part of this, but it looks like doing it all will require significant changes to the core types. `commenting` runs the writer, modified the `Rule`s, and then replaces them, which seems a little odd.

I'd eventually like to tackle

- [x] Annotating properties with comments.
- [ ] Commenting out lines (which would require a further change to the `Property` constructor).
- [ ] Writing longer comments (probably OK for selectors or in blocks but anywhere else and there's some significant refactoring to do).

That sound ok?

**Comment by turion** [comment]
If you're still planning on adding that, can you elaborate in a new issue and close this?

**Comment by dbaynard** [comment]
I do not still intend to add that — I'll close.
