### ISSUE TITLE
Add support for currentColor

### ISSUE THREAD

**Issue by adius** [sebastiaanvisser/clay#156]
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentColor_keyword

Full browser support: https://caniuse.com/#feat=currentcolor

**Comment by adius** [comment]
Workarount for the time being is `borderColor (other "currentColor")`

**Comment by turion** [comment]
That would be cool. PRs welcome.

**Comment by turion** [comment]
PING @ad-si
