### ISSUE TITLE
0.12.3 changed Property constructor

### ISSUE THREAD

**Issue by phadej** [sebastiaanvisser/clay#161]
This is breaking change, which according to [PVP](https://pvp.haskell.org/)  would require major version bump (i.e. 0.12.3 should been 0.13). Please pay attention to this in the future.

If `Rule` is meant to be opaque type, consider using `.Internal` modules, with a disclaimer that definitions are subject to change even in minor version bumps.

See https://github.com/fpco/stackage/issues/3336 and https://github.com/haskell-infra/hackage-trustees/issues/138

**Comment by seanparsons** [comment]
@phadej Is there something akin to Scala's MiMa that we can use to avoid breakages like this in the future?

**Comment by phadej** [comment]
@seanparsons good question, there is https://github.com/blitzcode/hackage-diff but I haven't used it in the past few years. It could be upgraded to use `cabal new-build` (or/and `stack`) so it don't need to play with sandboxes, then it will work nicely.

**Comment by seanparsons** [comment]
@phadej Hmmm, I might have a look at that this week.

**Comment by seanparsons** [comment]
@phadej I've pushed a 0.13.0 release and deprecated 0.12.3.

**Comment by phadej** [comment]
@seanparsons Thanks!
