### ISSUE TITLE
Font error (with the font method)

### ISSUE THREAD

**Issue by RamiroPastor** [sebastiaanvisser/clay#163]
The code: 
``` haskell
font
  ( Required (C.rem 1.2) Nothing ["Didact Gothic", "Verdana"] [sansSerif, serif] )
  ( Optional Nothing Nothing Nothing )

```

Produces: 

``` css
font :    1.19999rem "Didact Gothic","Verdana" sans-serif,serif;
```

Which is missing a comma. Is this intentional, and related to #19 ?

**Comment by RamiroPastor** [comment]
Btw i already had this issue some time ago, but now i find it more annoying, this:

```
instance ToCss (FontTheme a) where
  toCss = fontThemeToCss


fontThemeToCss :: FontTheme a -> Css
fontThemeToCss FontTheme {..} =
  font (ftOpt , ftReq)

```

Is being changed ...

**Comment by RamiroPastor** [comment]
... to this

``` haskell
instance ToCss (FontTheme a) where
  toCss = fontThemeToCss


fontThemeToCss :: FontTheme a -> Css
fontThemeToCss fontTheme =
  let
    (Required r1 r2 r3 r4) = ftReq fontTheme
    (Optional o1 o2 o3)    = ftOpt fontTheme
  in do
    fontSize r1
    maybe (pure ()) lineHeight r2
    fontFamily r3 r4
    maybe (pure ()) fontWeight  o1
    maybe (pure ()) fontVariant o2
    maybe (pure ()) fontStyle   o3
```

Whatever, not a big deal anyways

**Comment by turion** [comment]
Agree, there should probably be a comma. Do you want to fix this and add a regression test?

**Comment by RamiroPastor** [comment]
> Agree, there should probably be a comma. Do you want to fix this and add a regression test?

Maybe in the future, when i learn what is a regression test

**Comment by bsima** [comment]
> what is a regression test

It's a test that guards against this problem happening in the future,
i.e. it prevents a "regression".

**Comment by turion** [comment]
You could, for example, fix the issue and add exactly your example as a test. That would already be sufficient.
