### ISSUE TITLE
Variable not in scope: important

### ISSUE THREAD

**Issue by RamiroPastor** [sebastiaanvisser/clay#169]
The code:

``` haskell
import Clay.Stylesheet (important)
```

The error:

```
Module ‘Clay.Stylesheet’ does not export ‘important’
```

Found this one days ago but i didn't report it (because i didn't really need to use it)

When importing only Clay you get the "not in scope" version of the error

**Comment by dbaynard** [comment]
Which version are you using? (`important` was introduced in `0.13.0`.)

**Comment by RamiroPastor** [comment]
I'm using version 0.12.2 according to a stack command i just learned about (list-dependencies).

Should i upgrade to 0.13.0? Can i do it easily with stack?

**Comment by dbaynard** [comment]
The easiest way is to add to your stack.yaml,

```haskell
extra-deps:
- clay-0.13.0
```

In general, this introduces a risk that other libraries won't build with it, and you can see which might not be supported at <http://packdeps.haskellers.com/reverse/clay>. But you'll probably be fine.

Unfortunately, there's no workaround for `important` on earlier versions.

**Comment by RamiroPastor** [comment]
Thx!
