### ISSUE TITLE
Offer to help with maintenance

### ISSUE THREAD

**Issue by dbaynard** [sebastiaanvisser/clay#170]
Hello,

I'd be interested in helping maintain this library. On various projects I've used clay a lot, and having made a few PRs recently, I am reasonably familiar with the code. There's a fair amount of work needed to ensure the DSL matches the evolving CSS standard, and I'd like to make more regular contributions to that.

Let me know whether that would be helpful.

David

**Comment by seanparsons** [comment]
Related to your comment I've pondered in recent times about a code generation based approach because a few bugs in recent times have been things like typos which would just be entirely eliminated by doing something similar to the Amazonka libraries.

**Comment by dbaynard** [comment]
Good stuff — happy to help.

I think code generation is an excellent idea. I've had a few other thoughts, such as a (hint)[https://hackage.haskell.org/package/hint] based executable, a comprehensive test suite (which would play well with code generation), and there are a couple of outstanding issues which would be nice to resolve but require some heavy duty internal refactoring.

In general, I'd be happy to do an issue triage and flesh out a roadmap. A few things seem like low hanging fruit (such as getting clay back into stackage nightly) and I believe there are some CI issues (though I don't have any experience with that yet).

**Comment by turion** [comment]
@sebastiaanvisser @seanparsons @dbaynard 

It would be great to have you on board, if you're still up for that. I'm just getting started maintaining here, and I can already foresee that I'll only be able to review PRs, triage issues and keep the CI happy. I don't have the CSS knowledge to contribute nontrivial stuff, or figure out a roadmap.

**Comment by dbaynard** [comment]
Hi @turion 

Thanks for getting to this. As you see, my offer of help and the various comments/PRs were (in most cases) over a year ago. If there is now a solid plan for maintenance, then that is great to hear — but sadly, at the moment, I am unable to make the contributions clay needs.

That said, I do have some local changes and extensions which I will happily push, if there will be timely reviews. And I'll get to the various issues and PRs on which you've commented; hopefully this week.

**Comment by turion** [comment]
Thanks, that's already helpful! I'll review your changes the best I can.
