### ISSUE TITLE
Upload new version to hackage/stackage?

### ISSUE THREAD

**Issue by NickSeagull** [sebastiaanvisser/clay#172]
Hi, I maintain an app that uses Clay underneath, and some users are having trouble getting the latest version because it depends on Clay 0.13.0, which doesn't compile with GHC 8.4.

I saw that on `master` everything is fixed, could you upload these changes to Hackage or Stackage please?

Thanks in advance! :smile: :pray:

**Comment by seanparsons** [comment]
Yup, will be done, just been really busy.

**Comment by NickSeagull** [comment]
Thanks! Could you please mention me here when it's done so I can update my documentation?

**Comment by seanparsons** [comment]
@NickSeagull 0.13.1 now builds with GHC 8.4

**Comment by NickSeagull** [comment]
Thanks!
