### ISSUE TITLE
Incorrectly renders selectors like `*:before` or `*::before`

### ISSUE THREAD

**Issue by vyorkin** [sebastiaanvisser/clay#175]
Thanks for an awesome package!
Got a question regarding the rendering of `*`: could you please explain in a couple of words, why do you need this `null`-check here:
https://github.com/sebastiaanvisser/clay/blob/54dc9eaf0abd180ef9e35d97313062d99a02ee75/src/Clay/Render.hs#L302 ?

I'm asking because it seems that things like `*::before` will be rendered as just `::before` instead, which I'm not sure is correct.

Tests pass even after:
```
-            Star           -> if null ft then ["*"] else [""]
+            Star           -> ["*"]
```

**Comment by turion** [comment]
I don't know. Do you have a minimal example that produces wrong CSS?
