### ISSUE TITLE
wordBreak breakWord

### ISSUE THREAD

**Issue by phadej** [sebastiaanvisser/clay#183]
`break-word` is a valid `word-break`.

**Comment by turion** [comment]
Sorry, I'm not sure what you would like to see changed.

**Comment by phadej** [comment]
There's only `breakAll` and `keepAll` in https://hackage.haskell.org/package/clay-0.13.1/docs/Clay-Text.html#g:11

**Comment by turion** [comment]
Ah thanks :) unfortunately, that would clash with [`breakWord :: OverflowWrap`](https://hackage.haskell.org/package/clay-0.13.1/docs/Clay-Text.html#v:breakWord). Any idea how to resolve this?

**Comment by phadej** [comment]
I'd be fine with any solution:

```haskell
class BreakWord a where breakWord a
instance BreakWord OverflowWrap where ...
instance BreakWord WordBreak where ...
```

or 

```haskell
-- or any other non-clashing name
wordWordBreak :: WordBreak
```

**Comment by turion** [comment]
I find a `class Breakword a` the best solution here. It's the same as `class Initial` then for example. PRs welcome.

**Comment by phadej** [comment]
Unfortunately I'm not using `Clay` anymore, so someone else could fix this. I'm closing this issue so it's not on my open issues list.
