### ISSUE TITLE
Refinement -> Selector

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [sebastiaanvisser/clay#185]
I'm not sure if this is the same as #25 but it would be nice to have a function that converts a Refinement to a Selector.

Right now to just select on a class or an id we have to use `star # class_ "class-name"` which outputs `*.class-name`.

Would `sel = (#) $ selectorFromText "" :: Refinement -> Selector`  be an acceptable solution?

**Comment by BebeSparkelSparkel** [comment]
pr #186

**Comment by ddssff** [comment]
It is something that puzzled me for a while when I first started using clay the day before yesterday.

**Comment by turion** [comment]
@ddssff feel free to pick up #186 if you want :)

**Comment by ddssff** [comment]
Ok, I just need a little more experience.
