### ISSUE TITLE
How to get translate by percents?

### ISSUE THREAD

**Issue by NCrashed** [sebastiaanvisser/clay#188]
I'd like to get `transform: translateY(-50%);` in output, but http://hackage.haskell.org/package/clay-0.13.1/docs/Clay-Transform.html#v:translateY doesn't accept `Size Percentage`. Is it intentional design?

**Comment by NCrashed** [comment]
I found workaround:
``` haskell
translatePctY y = prefixed (browsers <> "transform") $ "translateY(" <> value y <> ")"
```

**Comment by turion** [comment]
> Is it intentional design?

Seems like an arbitrary restriction. https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateY#Syntax says one can translate by percentages. PRs that relax the typing constraints on the `translate*` functions welcome.
