### ISSUE TITLE
Hackage release process

### ISSUE THREAD

**Issue by turion** [sebastiaanvisser/clay#189]
Hi @sebastiaanvisser, I'll have to bother you with one last issue. To solve issues like #184, I'd need to have a way to upload to hackage (without creating my own fork). I see two ways how that might work:

1. Ideally, we could set up hackage deployment via Travis. If that's fine for you I'll create a MR where you (or someone else) can add a deploy key. If it works out the way I believe it should, every time I push a tag to the `master` branch, a new version should be uploaded.
2. Alternatively, you can give me access to the package on hackage somehow, and I can upload manually.

**Comment by sebastiaanvisser** [comment]
Is there a way for me to hand over the 'clay' namespace on Hackage to someone else? I guess you could just upload to it, right?

Honestly, I don't even see my Hackage account in my 1password which means the account might be lost. I might be able to ping a Hackage maintainer to help us out.

**Comment by turion** [comment]
I tried uploading, but I'm getting this error message:

```
You are not authorised to upload candidates of this package. The package 'clay' exists already and you are not a member of the maintainer group for this package. If you believe you should be a member of the maintainer group for this package, then ask an existing maintainer to add you to the group.
```

So yes, if you can't login to hackage, we probably need to contact a hackage maintainer.

**Comment by turion** [comment]
Or, easier (http://hackage.haskell.org/accounts):

> Reset password

> If you forget your password you can reset it so long as you know your user login name and the email address you originally registered with. The system will send you an email with a link you can use to set a new password.

**Comment by sebastiaanvisser** [comment]
Not going to work. It seems the account is connected to my uni e-mail, which hasn't been in use anymore for the past ten years.

**Comment by turion** [comment]
Dang. Well, I guess asking a hackage maintainer is the only option.

How did you give e.g. @seanparsons access?

**Comment by sebastiaanvisser** [comment]
I'm not sure I did. I think you can (or used to be able to) just upload new versions of someone else's packages.

**Comment by sebastiaanvisser** [comment]
Hi @turion, what is your hackage username? I'll forward it to a Hackage maintainer who can add you

**Comment by turion** [comment]
It's "turion" as well. Thanks!

**Comment by sebastiaanvisser** [comment]
Ok, the Hackage maintainer is a friend of mine and will probably fix this tonight.

**Comment by sebastiaanvisser** [comment]
done!

**Comment by turion** [comment]
Uploaded, it worked! Thanks for handing over :)
