### ISSUE TITLE
Get rid of build warnings related to monoids

### ISSUE THREAD

**Issue by turion** [sebastiaanvisser/clay#190]
When building with GHC 8.8, There are a lot of warnings like this:

```
The import of ‘Data.Semigroup’ is redundant
```

These places should be refactored to make build less noisy.

**Comment by Temurson** [comment]
Hello! I would love to fix this. Currently, I have cloned the repo and managed to build the project. I got the same warnings. I will try to make a PR soon (if I figure out how to do this).

**Comment by turion** [comment]
@Temurson thanks for your enthusiasm, but this issue was already fixed in #192. There are lots of other open issues, though ;)

**Comment by turion** [comment]
If you need any help making a PR, I'll gladly assist!
