### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by Temurson** [sebastiaanvisser/clay#194]
I have downloaded Clay and tried playing around with, when I found that the single example in "examples" folder is broken - it has a bunch of errors both in Main.hs and generate.sh script. The errors do not depend on the compiler or any environment, just pure programming errors. I suspect they appeared after adding new features / deprecating the old ones.

The errors:
1) generate.sh - path to search for modules jumps two directories upwards instead of one.
2) Main.hs - Incompatibilities with Double vs Integer (probably Size type accepted Integer instead of Double before)
3) Main.hs - boxShadow function has changed its signature, the one that is expected is now called boxShadow', and is deprecated. Need to update to the new version.

Is that something you are aware of? I am almost done fixing it, and I would like to make a pull request with the fixed version. Is that something you would like to see?

**Comment by turion** [comment]
Good catch! I didn't pay attention to that folder. Fixes to it would be most welcome!

If you want and can, it would be great to add the example to the CI as well (possibly in a separate PR).

**Comment by Temurson** [comment]
I have fixed the example, and now it compiles and works properly. I am creating a PR for this now. However, I would like to note one strange problem I ran into while doing fixing all that. When I was done, I tried to test the example, but it didn't work saying that mtl is a hidden package. It took me a while, but I figured that this was because the file .ghc/x86_64-linux-8.8.1/environments/default, which contains the default packages exposed when using ghc (and runhaskell command, which generate.sh uses in the example), did not have mtl-2.2.2 listed. I have no idea how this happened, and could not finding anything meaningful except for the comment from someone that they "nuke .ghc folder" once in a while. So I did that and everything worked on every compiler supported by Clay. This is probably not related to Clay, but do you have any idea why this could happen?

**Comment by turion** [comment]
> this was because the file .ghc/x86_64-linux-8.8.1/environments/default, which contains the default packages exposed when using ghc (and runhaskell command, which generate.sh uses in the example), did not have mtl-2.2.2 listed

This sounds unrelated to clay indeed. Because of these kinds of issues, we build everything reproducibly with [`nix`](https://nixos.org/nix/).

You needn't worry about the CI, actually. But if you can get `nix` to run, and build Clay with it, we can work on including the example in there :) I'll open a separate issue for you.

**Comment by Temurson** [comment]
#195
