### ISSUE TITLE
Prefix the `sticky` `position` value

### ISSUE THREAD

**Issue by 414owen** [sebastiaanvisser/clay#202]
Apple browsers support sticky positions iff prefixed with `-webkit-` ([source](https://caniuse.com/#feat=css-sticky)).
I'm happy to create a PR for this, but I want to check one thing first -- because `-webkit-` is the only prefix, is it okay if I bypass the `browsers` `Prefixed`?

**Comment by turion** [comment]
You're welcome to create a PR!

I'm not sure yet how your solution will work exactly, but we'll get there in your PR. Try it the way you proposed, and we'll find out.

Background: It seems that this is actually a workaround for Safari, since all other major browsers support simply `sticky`.
