### ISSUE TITLE
`Visibility` instances

### ISSUE THREAD

**Issue by nsaunders** [sebastiaanvisser/clay#224]
See https://github.com/sebastiaanvisser/clay/blob/master/src/Clay/Display.hs#L189

* `Visibility` _should not_ have an `Auto` instance because `auto` is not a valid value for the `visibility` property
  * [MDN Web Docs: visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#syntax)
  * <img width="177" alt="image" src="https://user-images.githubusercontent.com/2517229/156363325-50fb9a58-c86a-4bbd-b269-5ba60541a3dd.png">
* `Visibility` _should_ have an `Unset` instance
  * [MDN Web Docs: visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#syntax)

**Comment by turion** [comment]
Makes sense, PR welcome :)
