### ISSUE TITLE
Move CI from Travis to Github Actions

### ISSUE THREAD

**Issue by turion** [sebastiaanvisser/clay#230]
Travis seems more and more closed for open source projects. It's better to get rid of the hassle and move to Github Actions.

**Comment by turion** [comment]
It would be nice to test the Nix build as well though.

**Comment by tomjaguarpaw** [comment]
I don't think I did it, but yes, seems like it was done in fd2b9aeac703f28ea6400003616ae28110da3d8f, https://github.com/sebastiaanvisser/clay/pull/231. That PR says that it is "Part of https://github.com/sebastiaanvisser/clay/issues/230". I don't know what the remaining parts are supposed to be.

**Comment by turion** [comment]
The remaining bit to do is:

> It would be nice to test the Nix build as well though.

**Comment by turion** [comment]
But it would be fine to open a separate ticket for that and close this one.

**Comment by turion** [comment]
The remainder is #196
