### ISSUE TITLE
not selector cannot be applied to a refinement

### ISSUE THREAD

**Issue by Skyfold** [sebastiaanvisser/clay#239]
The not selector can be applied to a selector `:not(p)` or to a refinement `input:not(:checked)`, however the type signature for not is `not :: Selector -> Refinement`.

What I need is effectively `not :: Either Selector Refinement -> Refinement`, though it would not be nice to write `input # not (Left checked)`. Ideally, I would like to write `not p` and `input # not checked`. 

How would you like this implemented?

**Comment by turion** [comment]
Thanks for pointing this out!

The typical `clay` style for this is to create a new type class:

```haskell
class Not a where
  not :: a -> Refinement

instance Not Selector where
...
instance Not Refinement where
...
```

So rather an open sum than a closed sum.

**Comment by turion** [comment]
Feel free to send a PR if you want :)

**Comment by turion** [comment]
Thanks!
