### ISSUE TITLE
When building with GHCJS, test cases fail but results look ok

### ISSUE THREAD

**Issue by ddssff** [sebastiaanvisser/clay#242]
Because GHCJS has different word sizes, the equality tests that work in GHC fail.  For example,
```
     13) Clay.Color.darken does not darken an HSL color past black
       expected: Hsla 154 0.787 9.2e-2 255.0
        but got: Hsla 154 0.787 9.2e-2 255.0
```
The tests must be using equality when "close enough" is what we need.

**Comment by turion** [comment]
That's a puzzling error message :sweat_smile: . So we'd first need a working CI check that runs clay on GHCJS, and then fix the tests. PRs welcome.

**Comment by ddssff** [comment]
What is the situtation with CI these days?  I lost track when travis disappeared.

**Comment by turion** [comment]
We have Github Actions with Ubuntu & cabal: https://github.com/sebastiaanvisser/clay/blob/master/.github/workflows/ci.yml But I have no idea whether one can GHCJS there. Maybe we should also reinstate the nix CI job.

**Comment by turion** [comment]
The state of this issue is still: I'd accept a PR that adds a nix CI job that also builds & tests with GHCJS. But if there is not enough interest in this it's also fine to pass on this and look at it again with the JS & WASM backends of GHC 9.10.

**Comment by ddssff** [comment]
We are close to upgrading to the new back ends.

**Comment by turion** [comment]
I guess it makes more sense to skip on GHCJS then. The ecosystem will have to move. Feel free to open a new issue on the new backends, should the tests still fail there.

**Comment by ddssff** [comment]
I expect the issue will remain the same, but I'll keep my eye on it.  Though having this bug open would help jog my memory.
