### ISSUE TITLE
Please bump base upper bound on Hackage

### ISSUE THREAD

**Issue by tomjaguarpaw** [sebastiaanvisser/clay#255]
The git repo [supports 9.4](https://github.com/sebastiaanvisser/clay/commit/e97840e3fa396a60685829fe3f4e86838bebf774) but could you please bump the Hackage upper bound on base to `< 4.18` too? Currently [it's at `< 4.16`](https://hackage.haskell.org/package/clay).

**Comment by tomjaguarpaw** [comment]
Do you need any help with this? I'm willing to act as a comaintainer if you like.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/clay-0.14.0/revisions/

**Comment by turion** [comment]
>  I'm willing to act as a comaintainer if you like.

@tomjaguarpaw yes, I'd appreciate this a lot! I've interacted several times with you (e.g. a PR on `free`) and it has been friendly and professional every time.

I currently don't have that much time to spare on `clay`, so an extra hand would be very helpful. What is your Hackage username?

**Comment by tomjaguarpaw** [comment]
I am `tomjaguarpaw`: https://hackage.haskell.org/user/tomjaguarpaw

**Comment by turion** [comment]
Excellent, I've added you as a maintainer for `clay`.

**Comment by tomjaguarpaw** [comment]
This has been resolved.
