### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by chungyc** [sebastiaanvisser/clay#257]
It's approaching two years since the last release.  Maybe it's time to do another release with version bound updates and a new upload to Hackage?

Just a thought.

**Comment by turion** [comment]
@tomjaguarpaw do you still have the capacity to create hackage releases?

**Comment by tomjaguarpaw** [comment]
> do you still have the capacity to create hackage releases?

Yes, I have. Are you asking me to do a release? I can do that. I notice that the API has broken significantly since `0.14` so it would be good to include release notes explaining what has changed.

**Comment by tomjaguarpaw** [comment]
And this really ought to be in before release https://github.com/sebastiaanvisser/clay/pull/258

**Comment by turion** [comment]
> > do you still have the capacity to create hackage releases?
> 
> Yes, I have. Are you asking me to do a release? I can do that. I notice that the API has broken significantly since `0.14` so it would be good to include release notes explaining what has changed.

Yes, please :) I agree about the release notes.

**Comment by tomjaguarpaw** [comment]
I intend to release to Hackage once the updated CHANGELOG is merged https://github.com/sebastiaanvisser/clay/pull/260

**Comment by tomjaguarpaw** [comment]
Released at https://hackage.haskell.org/package/clay-0.15.0
