### ISSUE TITLE
Support `aspect-ratio` CSS property

### ISSUE THREAD

**Issue by chungyc** [sebastiaanvisser/clay#259]
Add support for the [`aspect-ratio` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio).  It specifies a desired aspect ratio for a display element.

*  `auto`
*  ratios in the form of `1/1`, `16/9`, `2`, or `0.5`
*  fallback values with `auto` and a ratio; e.g., `auto 1/1` or `1/1 auto`
*  one of `inherit`, `initial`, `revert`, `revert-layer`, `unset`

I think we can support this by adding an `aspectRatio` function to `Clay.Geometry`.  Its argument could be a [`Rational`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Ratio.html) for ratios, a tuple of (`auto`, ratio) or (ratio, `auto`), or the usual set of `auto`, `inherit`, ... values.  Its argument type could be a type class like `AspectRatioValue`, of which `Rational` and `Value` could be made instances.  E.g.,

```haskell
aspectRatio auto
aspectRatio initial
aspectRatio (16%9)
aspectRatio (16%9, auto)
```

This issue is mainly stating my intention to implement support for `aspect-ratio` and to track any work related to it, rather than a feature request for someone else to implement.

Note that this is distinct from the [`aspect-ratio` media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio), which is already supported with [`Clay.Media.aspectRatio`](https://hackage.haskell.org/package/clay-0.14.0/docs/Clay-Media.html#v:aspectRatio).

**Comment by turion** [comment]
That sounds like a great addition! Note that `aspect-ratio: auto 3/4;` is also valid CSS. Do you want to submit a PR?

**Comment by chungyc** [comment]
> Do you want to submit a PR?

That's my plan ... eventually.
