### ISSUE TITLE
Maybe ditch the Num instances for sizes

### ISSUE THREAD

**Issue by jameshfisher** [sebastiaanvisser/clay#31]

**Comment by andrewthad** [comment]
The Num instances for Size are gone. This should be closed.

**Comment by turion** [comment]
Well, there are still/again `Num` instances for `Size LengthUnit` and `Size Percentage` that don't do anything else than providing `fromInteger`. It's a bit ridiculous that all methods like `+` and so on are not implemented, and throw an error instead.

Fixing this issue would entail (IMO) to implement at least `(+), abs, negate` for these two `Size`s, and documenting in Haddock above the instance that it is not fully implemented.
