### ISSUE TITLE
Semigroup on refinements?

### ISSUE THREAD

**Issue by ocharles** [sebastiaanvisser/clay#53]
I wanted to set `outline-style:none` for both `a:active` and `a:visited`, and thought I could do `(":active" <> ":hover") & outlineStyle none`, but `Refinement` is not a `Monoid` or `Semigroup` instance. In the end I did:

``` haskell
forM_ [":active", ":focus"] (& outlineStyle none)
```

Which does the job, but it is a tad verbose.

It also doesn't produce `a:active, a:focus` as I wanted, but instead gives me two separate blocks.

**Comment by jhenahan** [comment]
I'm a bit curious about how you'd like this to work in certain cases.

With the trivial Monoid instance I'm playing with, this renders as `a:active:hover`, which is not what you want, but I think it fits the spirit of the Monoid better. I'm mainly thinking about cases like`a:hover:last-child`.

Conceptually, I think this is the right way to make Refinement a Monoid, but I'm open to being convinced that the split case is the better default.

**Comment by ocharles** [comment]
I agree that what your suggesting. I can't say I gave the semigroup much thought, but seeing as pseudo selectors "stack" I'd be ok with your proposal.

**Comment by Profpatsch** [comment]
I stumbled over `Refinements` not being a semigroup, too. But I think what the OP wants is not what the instance should be: `a:focus:hover` selects all elements that are focused *and* hovered over.

So it would more sense to make it a commutative semigroup that combines its effects in that manner.

**Comment by turion** [comment]
I guess it would make sense to make `Refinement` a `Semigroup`, but I'm not sure I understand this well enough. PR welcome.
