### ISSUE TITLE
move the sym functions out of Size.hs

### ISSUE THREAD

**Issue by jameshfisher** [sebastiaanvisser/clay#62]

**Comment by turion** [comment]
Hi @jameshfisher, new maintainer here. You reported a lot of issues some 6 1/2 years ago. Do you think someone (maybe you? ;) ) might work on them? Or at least triage and find out which issues are still valid?

**Comment by jameshfisher** [comment]
Late reply here - sorry, I no longer use clay, and don't have time to maintain it! Closing this issue is sensible
