### ISSUE TITLE
Full monoid instance for Selector

### ISSUE THREAD

**Issue by piyush-kurur** [sebastiaanvisser/clay#68]
I would have loved if Selector was a full monoid. I could have written `mconcat` 
instead of using a auxilary function like `selectors` as in

https://github.com/piyush-kurur/pottery/blob/master/Pottery/Reset.hs

While it is understandable that there is no such thing as an empty list of selector, may be we can invent one called EmptySelector and report error in the css monad instead
when we try some thing like 

``` haskell

EmptySelector ? do
     background black
```

This `EmptySelector` can then be the `mzero`

**Comment by jhenahan** [comment]
What about a `Semigroup`? It'll require some extra machinery to ensure that only `NonEmpty` lists of selectors can be created, but then we can just use `sconcat`.

**Comment by turion** [comment]
It currently is a `Semigroup`, but the `Monoid` instance is a bit embarassing because it simply `error`s on `mempty`. What would be a good value for `mempty`?
