### ISSUE TITLE
Provide CLI tool for building stylesheets

### ISSUE THREAD

**Issue by singpolyma** [sebastiaanvisser/clay#70]
The idea is that the tool would take files that have Clay code in them, generate a file with the correct trivial import, `main`, and extensions added, and compile and run this (or just use `runhaskell`).

**Comment by Heather** [comment]
:+1: yes I think it will be more intuitive to use. Do you plan to make it alike following:

``` shell
clay clay1.hs > css.css
clay clay2.hs >> css.css
```

I think also good idea will be add option for `compress` alike here : https://github.com/jaspervdj/hakyll/blob/7f7c628823f159690c10393ab1b4c5c45c4c52d1/src/Hakyll/Web/CompressCss.hs

**Comment by turion** [comment]
Sounds like a good idea. PR with a test welcome. Ideally, test it on CI with Nix.
