### ISSUE TITLE
Margins cannot be percentages

### ISSUE THREAD

**Issue by jameswilddev** [sebastiaanvisser/clay#79]
Hello!  Quite enjoying your framework!  Very easy to use!

When trying to set a margin using a percentage (example: margin (pct 25) 0 0 0) I get a compile error stating:
  Couldn't match expected type 'Abs' with actual type 'Rel'

Looks like margins have been implemented as something you have to specify an exact width for rather than a width relative to the parent container.  Quite straightforward to work around for the moment.

Thank you!

**Comment by Heather** [comment]
``` haskell
margin :: Size a -> Size a -> Size a -> Size a -> Css
margin a b c d = key "margin"  (a ! b ! c ! d)
```

Not sure if just `0` could be treated as `Size` for now

for your situation currently it's better to use one of `marginTop, marginLeft, marginRight, marginBottom`

**Comment by bryangarza** [comment]
I think you have to use `nil`, not 0.

**Comment by turion** [comment]
I'm not sure what's a good resolution here. If anyone has an idea, feel free to send a PR :)
