### ISSUE TITLE
Support for calc() would be nice

### ISSUE THREAD

**Issue by beeramtheman** [sebastiaanvisser/clay#90]
Really love the framework, but I noticed it doesn't have built-in support the really handy calc() function. Of course for now one can get around this with the Other type class.

For those that don't know: https://developer.mozilla.org/en-US/docs/Web/CSS/calc

```
width: calc(50% - 10px);
```

**Comment by sebastiaanvisser** [comment]
Yes, that would be nice. This should be reasonably easy to embed into some mini expression type.

**Comment by BebeSparkelSparkel** [comment]
@bramgg Did you figure this out?

**Comment by tomsmalley** [comment]
@BebeSparkelSparkel see `Clay.Size`: https://hackage.haskell.org/package/clay-0.13.1/docs/Clay-Size.html#v:-64--43--64-

**Comment by turion** [comment]
There is an interface for basic calculations (`+, -, *, /`).
