### ISSUE TITLE
Css property justify-content missing

### ISSUE THREAD

**Issue by rekahsoft** [sebastiaanvisser/clay#91]

**Comment by 3noch** [comment]
:+1:

**Comment by 3noch** [comment]
I see this is in `master`. Is there a reason this is not on Hackage yet?

**Comment by marcelbuesing** [comment]
@3noch I have been waiting for a new release since Feb 2015 for the flex related stuff. As a workaround if you are using stack, you may directly reference the git repository and commit ([details](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#packages)).

**Comment by 3noch** [comment]
@marcelbuesing Thanks! I'll do that. It seems @sebastiaanvisser is still actively maintaining this repo so I wonder why Hackage is so out-of-date.

**Comment by BebeSparkelSparkel** [comment]
Seems like this should be closed
