### ISSUE TITLE
Unable to set value to "initial" of the content property

### ISSUE THREAD

**Issue by rekahsoft** [sebastiaanvisser/clay#92]
Unable to specify "initial" for the css property "content". It seems to me that this is because the Content type doesn't implement the Initial typeclass? But after looking through the clay source I didn't find many types that actually derived it. This seems a little odd as the "initial" value is valid for all css properties.

Also because the Content type doesn't implement the Other typeclass ```content (other "initial)``` cannot be used and instead one has to override using the following:

``` haskell
"content" -: "initial"
```

Maybe I misunderstand how to use inital in clay. Please correct me if I'm wrong.

**Comment by sebastiaanvisser** [comment]
This was just never implemented, but is now thanks to @Heather.

**Comment by Heather** [comment]
@sebastiaanvisser sorry for offtopic but what do you think about conflicts alike here: https://github.com/sebastiaanvisser/clay/pull/93

**Comment by sebastiaanvisser** [comment]
@Heather I think for values that are common between 'quite a lot' of css properties a type class makes a lot of sense. For values that are only shared between one or two properties I prefer to have two prefixed identifier. 

Not sure where the threshold is, matter of taste I guess.
