### ISSUE TITLE
Export Selector Rendering

### ISSUE THREAD

**Issue by jfischoff** [sebastiaanvisser/clay#95]
I like the selector combinators and would like to use them in a situation where I only need selector printing (Selenium tests). 

It would be great if the Selector rendering function (https://github.com/sebastiaanvisser/clay/blob/master/src/Clay/Render.hs#L245) was exposed.

**Comment by jfischoff** [comment]
A pull request oh 2e27fc923ff23985d49e6e64f71632ca98cc31cb I see

**Comment by jfischoff** [comment]
You're too fast ;)

**Comment by jfischoff** [comment]
can you release a new minor version of this?

**Comment by sebastiaanvisser** [comment]
Haha! Do you think we need the `With` version as well?

**Comment by sebastiaanvisser** [comment]
For a single selector it doesn't feel useful to include newlines, but maybe you have a use case for this.

**Comment by jfischoff** [comment]
No I just added it for consistency

**Comment by sebastiaanvisser** [comment]
There you go: http://hackage.haskell.org/package/clay-0.10.1

Thanks!

**Comment by jfischoff** [comment]
Thank you!
