### ISSUE TITLE
`center` missing for `textAlign`

### ISSUE THREAD

**Issue by ocharles** [sebastiaanvisser/clay#97]
The only way to produce 

```css
text-align: center
```

is with

```haskell
textAlign (other "center")
```

which seems a bit weird, as it's a standard property value.

**Comment by sebastiaanvisser** [comment]
It's not pretty, but the 'official' way of doing it is like this:

`textAlign (alignSide sideCenter)`

**Comment by sebastiaanvisser** [comment]
`center` currently isn't used anywhere else, so it does make sense to use it directly for `text-align` as well.

**Comment by sebastiaanvisser** [comment]
Thanks, you can now use `textAlign center` directly, because it is the most obvious use case for `center` I can think of.
