### ISSUE TITLE
No way to specify "spread" property of box-shadow

### ISSUE THREAD

**Issue by ocharles** [sebastiaanvisser/clay#98]
`boxShadow` takes three sizes, but the property actually has [four](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow). I can of course use `-:`, but I think `clay` needs to be updated to match the spec.

**Comment by Heather** [comment]
what clay really needs is optional arguments...

**Comment by seanparsons** [comment]
`boxShadowWithSpread` is in there, oddly it wasn't exported previously.
